### ISSUE TITLE
Reading HDF5 files

### ISSUE THREAD

**Issue by fadilmyounes** [frankchen121212/High-Resolution-MoonNet#2]
I did not know how to read the dataset files, could you please explain it for me ?

**Comment by frankchen121212** [comment]
For our data, you can refer to the following suggestions:

After downloading the dataset, please make sure to put all the folders in the the directory:data and make them looks like this:

├── data
│   ├── assembled_dataset
│   │   ├── assembled_dataset.hdf5
│   │   ├── assembled_train.hdf5
│   │   └── assembled_val.hdf5
│   ├── deepmoon
│   │   ├── dev_craters.hdf5
│   │   ├── dev_images.hdf5
│   │   ├── test_craters.hdf5
│   │   ├── test_images.hdf5
│   │   ├── train_craters.hdf5
│   │   ├── train_images.hdf5
│   │   └── Using\ Zenodo\ Data.ipynb
│   └── surfacecrack
│       └── surface_crack.hdf5


For hdf5 file format, python has the library for reading it, you will just need to import as the following:

import h5py

Technical details could be referred to official document:

https://docs.h5py.org/en/stable/

 Or StackOverflow:

 https://stackoverflow.com/questions/28170623/how-to-read-hdf5-files-in-python
